#!/usr/bin/env node
'use strict';

var LamassuConfig = require('lamassu-config');
var promptly = require('promptly');

var config = new LamassuConfig();

console.log('\nSetting up the BitStamp ticker and trader plugin.\n');
console.log('Please enter your API credentials.\n');
promptly.prompt('ID: ', function(clientIdErr, clientId) {
  promptly.prompt('API Key: ', function(keyErr, key) {
    promptly.password('Secret: ', function(secretErr, secret) {
      updateDb(clientId, key, secret, function(err) {
        if (err) throw err;
        console.log('\nSuccess.');
      });
    });
  });
});

function updateDb(clientId, key, secret, callback) {
  var newConfig = {
    exchanges: {
      plugins: {
        settings: {
          bitstamp: {
            key: key,
            clientId: clientId,
            secret: secret
          }
        },
        current: {
          ticker: 'bitstamp',
          trade: 'bitstamp'
        }
      }
    }
  };
  config.mergeConfig(newConfig, callback);
}
